site_name: ML-Git
site_url: "https://hpinc.github.io/ml-git/"
nav:
  - Home:
    - Introduction: index.md
    - Getting Started: first_steps.md
    - Additional Use Cases: advanced_scenarios.md
    - Architecture: 
      - Design: mlgit_internals.md
      - Cache and Objects: centralized_cache_and_objects.md
      - Mutability Helper: mutability_helper.md
      - Plugins: plugins.md
      - Resources Initialization: resources_initialization.md
      - Working With Tabular Data: tabular_data/tabular_data.md
    - Supported Storages:
      - Configurations: storage_configurations.md
      - MinIO: minio_s3_configuration.md
      - S3: aws_s3_configuration.md
      - Azure: azure_configurations.md
      - Google Drive: gdrive_configurations.md
    - Commands:
      - Using ML-Git CLI: mlgit_commands.md
      - Using ML-Git API:
        - Quick Start: api/quick_start.md
        - Methods: api/README.md
    - Docker Environment: downloadable_environment.md
    - ML-Git Step-by-Step Guides: step_by_step_guides.md
      - Basic Flow: api/api_scripts_docs/basic/basic_flow.md
      - Clone Repository: api/api_scripts_docs/basic/clone_repository.md
      - Multiple Projects: api/api_scripts_docs/basic/multiple_projects.md
      - Relationship API Commands: api/api_scripts_docs/relationship_notebook/relationship_api_commands.md
      - MNIST Random Forest API: api/api_scripts_docs/mnist_notebook/mnist_random_forest_api.md
      - MNIST Random Forest CLI: api/api_scripts_docs/mnist_notebook/mnist_random_forest_cli.md
      - Checkout With Sample: api/api_scripts_docs/multiple_datasets_notebook/checkout_with_sample.md
      - Multiple Datasets: api/api_scripts_docs/multiple_datasets_notebook/multiple_datasets.md
  - Contributing to ML-Git: developer_info.md

  
theme:
  name: "material"
  # logo: img/small_icon.png
  # favicon: img/fav_icon.png
  palette:
    primary: light blue
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - toc:
     permalink: true

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
