name: 'Install dependencies'
description: 'Install ml-git dependencies'

runs:
  using: 'composite'
  steps:
      - run: |
          python -m pip install --upgrade pip
          pip install pipenv==2021.5.29
          pip install pytest==5.3.5
          pip install flake8==3.9.2
        shell: bash
