name: MLGit-CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: 
      - development
      - bugfix/**

jobs:
  flake8:
    name: Flake8

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Lint with flake8
        run: |
          flake8 .

  convert-notebooks:
    name: Convert Jupyter Notebooks to Markdown
#    needs: [flake8, build-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: 'https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/'

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Create empty Markdowns
        run: |
          for jupyter_file in $(find ./docs/api -name '*.ipynb'); do
              touch "${jupyter_file%.ipynb}.md";
          done

      - uses: runsascoded/nbconvert@v1.2
        with:
          args: -f -a
