name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: 'https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/'
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Convert Notebooks to Markdown
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install notebook
          for jupyter_file in $(find ./docs -name '*.ipynb'); do
              jupyter nbconvert --to markdown "${jupyter_file}";
          done
      - name: Create index
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "docs/index.md"
      - name: Create downloadable environment
        uses: canastro/copy-file-action@master
        with:
          source: "docker/README.md"
          target: "docs/downloadable_environment.md"
      - name: ML-Git Step-by-Step Guides
        uses: canastro/copy-file-action@master
        with:
          source: docs/api/api_scripts/README.md
          target: docs/step_by_step_guides.md
      - name: Remove 'docs/' from links - step 1
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: docs\/
          replace: " "
          include: "docs/index.md"
      - name: Remove 'docs/' from links - step 2
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: \.md
          replace: " "
          include: "docs/index.md"
      - name: Remove 'docs/' from links - step 3
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: README
          replace: " "
          include: "docs/index.md"
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material
          python3 -m pip install mkdocs-git-revision-date-localized-plugin
      - name: Build site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./site
