name: MLGit-Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build Linux

    runs-on: ubuntu-latest

    env:
      BUILD_NAME: 0
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Build
        run: |
         pipenv --python 3.6
         chmod +x ./scripts/build/compile/build.sh
         make build

      - name: Define build name
        run: |
          echo -ne $(cat version.info | grep MAJOR_VERSION | cut -d"=" -f2). >> BUILD_UBUNTU_FILE
          echo -ne $(cat version.info | grep MINOR_VERSION | cut -d"=" -f2). >> BUILD_UBUNTU_FILE
          echo -ne $(cat version.info | grep PATCH_VERSION | cut -d"=" -f2) >> BUILD_UBUNTU_FILE
          BUILD_VERSION="$( cat BUILD_UBUNTU_FILE )"
          echo 'BUILD_NAME='${BUILD_VERSION} >> $GITHUB_ENV

      - name: Release Build
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{env.BUILD_NAME}}
          path: dist/*.gz
        if: ${{ always() }}

  build-windows:
    name: Build windows

    runs-on: windows-latest

    env:
      BUILD_NAME: 0
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Build
        run: |
         pipenv --python 3.6
         .\scripts\build\compile\build.bat
        shell: cmd

      - name: Define build name
        run: |
          echo -ne $(cat version.info | grep MAJOR_VERSION | cut -d"=" -f2). >> BUILD_WINDOWS_FILE
          echo -ne $(cat version.info | grep MINOR_VERSION | cut -d"=" -f2). >> BUILD_WINDOWS_FILE
          echo -ne $(cat version.info | grep PATCH_VERSION | cut -d"=" -f2) >> BUILD_WINDOWS_FILE
          BUILD_VERSION="$( cat BUILD_WINDOWS_FILE )"
          echo 'BUILD_NAME='${BUILD_VERSION} >> $GITHUB_ENV
        shell: bash

      - name: Release Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{env.BUILD_NAME}}
          path: dist/*.gz
        if: ${{ always() }}

  flake8:
    name: Flake8
    needs: [build-linux, build-windows]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Lint with flake8
        run: |
          flake8 .

  unit-tests:
    name: Unit Tests
    needs: [build-linux, build-windows]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: 'https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/'

      - name: Configure Git Credentials for Tests
        uses: ./.github/actions/configure_git_credentials

      - name: Unit Tests
        run: |
          pipenv --python 3.6
          chmod +x ./scripts/run_unit_tests.sh
          make test.unit

      - name: Archive code coverage results of unit tests
        uses: actions/upload-artifact@v1
        with:
          name: ut-code-coverage-report
          path: tests/unit/unit_tests_coverage
        if: ${{ always() }}


  integration-tests:
    name: Integration Tests
    needs: [build-linux, build-windows]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: 'https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/'

      - name: Configure Git Credentials for Tests
        uses: ./.github/actions/configure_git_credentials

      - name: Integration Tests
        run: |
          pipenv --python 3.6
          chmod +x ./scripts/run_integration_tests.sh
          make test.integration

      - name: Archive code coverage results of integration tests
        uses: actions/upload-artifact@v1
        with:
          name: it-code-coverage-report
          path: tests/integration/integration_tests_coverage
        if: ${{ always() }}